# E:\A1QA\automation\pytest.ini
[pytest]
# Pytest ko bolo ki Playwright ki library use karni hai
# Aur yeh bhi batao ki test files 'test_' se shuru honi chahiye.
addopts = -p playwright
testpaths = tests